### ISSUE TITLE
error when trying to merge

### ISSUE THREAD

**Issue by mmmurf** [MostWantIT/react-native-video-editor#1]
Hello, when I try to merge some videos I get this error. Advice much appreciated. 

Exception '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array' was thrown while invoking merge on target RNVideoEditor with params (
        (
        "assets-library://asset/asset.mov?id=35704C4B-CA5C-452A-9FA3-B23ABFB68879&ext=mov",
        "assets-library://asset/asset.mov?id=37FDF315-F206-4A21-B321-D94213B165CF&ext=mov"
    ),
    488,
    489
)

**Comment by Antonides** [comment]
The file url/path you use is incorrect. You need absolute path to the video. What do you use to generate the movie?

**Comment by mmmurf** [comment]
Using react-native-camera to generate the movies, also tried converting to mp4 before merging.  Above I was using assets-library URLs but it seems to be having the same error with absolute paths to mov or mp4 files.  

Exception '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array' was thrown while invoking merge on target RNVideoEditor with params (
        (
        "/private/var/mobile/Containers/Data/Application/A02903B3-26D0-4309-98AA-0FB686B5135E/tmp/A07BFD94-F2C4-4236-820B-3DA964839CE1-8179-000007F0A8F8A9EA.mov",
        "/private/var/mobile/Containers/Data/Application/A02903B3-26D0-4309-98AA-0FB686B5135E/tmp/621CDF00-DA01-468A-AB4C-0BF18A87FBEF-8179-000007F0AD1D2D97.mov"
    ),
    492,
    493
)



this also fails: 

Exception '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array' was thrown while invoking merge on target RNVideoEditor with params (
        (
        "/private/var/mobile/Containers/Data/Application/E5C9702F-0E40-4E8B-8035-BD59756C5F84/Documents/9BA8340C-8A12-4F25-9ACF-2ECA40DE096B-8186-000007F2EE31D6CC.mp4",
        "/private/var/mobile/Containers/Data/Application/E5C9702F-0E40-4E8B-8035-BD59756C5F84/Documents/748AB8E5-56FC-48DD-8027-40D1EB10C65A-8186-000007F2F300584C.mp4"
    ),
    492,
    493
)

**Comment by mmmurf** [comment]
Figured it out, the file "url" in the objc code does not want the file:// string prefixed to it. Also, the file I was testing did not have an audio track and this caused the merge to fail also.

I'd suggest adding some additional input validation and error output, I can do a PR at some point in the next few weeks if you want.

**Comment by Antonides** [comment]
That would be nice. Tnx.

**Comment by ajaxmac** [comment]
I found that when recording with react-native-camera saving to temp got this library working for me (Camera.constants.CaptureTarget.temp)
