### ISSUE TITLE
React/RCTDefines.h File Not Found Error

### ISSUE THREAD

**Issue by BhuwaneshSisodia** [MostWantIT/react-native-video-editor#14]
After linking the library with ios facing this error 
**"/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found"** under Lexical or Preprocessor Issue of RNVideoEditor.

![Screenshot 2019-08-02 at 4 36 55 PM](https://user-images.githubusercontent.com/19169880/62366273-1074bb80-b544-11e9-9b4e-a2a627a40c13.png)

> In file included from /Users/bhuvi/Documents/videomerger/node_modules/react-native-video-editor/ios/RNVideoEditor.m:2:
> In file included from /Users/bhuvi/Documents/videomerger/node_modules/react-native-video-editor/ios/RNVideoEditor.h:2:
> ../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
> #import <React/RCTDefines.h>
>         ^~~~~~~~~~~~~~~~~~~~
> 1 error generated.

Followed every step but just getting Build Failed. But working fine in Android Studio.

**My Package.json file**
{
  "name": "videomerger",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-camera": "^3.0.0",
    "react-native-image-crop-picker": "^0.25.0",
    "react-native-video": "^5.0.0",
    "react-native-video-editor": "^0.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.8.0",
    "eslint": "6.1.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by dev3288** [comment]
https://github.com/joltup/rn-fetch-blob/issues/461#issuecomment-553355501
