### ISSUE TITLE
Rotated video file

### ISSUE THREAD

**Issue by bsiddiqui** [MostWantIT/react-native-video-editor#8]
If I save the file returned by `RNVideoEditor.merge()` to the Camera Roll, the video is rotated 90 degrees. If I save the same file without passing it to `.merge()` it saves correctly. I called merge with only one file to make sure this rotation wasn't being caused by a difference in video orientations.

**Comment by Antonides** [comment]
This is happening in this file:

https://github.com/MostWantIT/react-native-video-editor/blob/master/ios/RNVideoEditor.m#L67

Maybe you can comment it out. and check again.

**Comment by bsiddiqui** [comment]
@Antonides yeah it appears that videos created elsewhere don't need to be rotated but videos generated by the camera need to be rotated to export correctly. Not a bug so I'll close but it would be great if the module took orientation into consideration. If I get some time later I'll take a look at it.
